name       : user-manager
version    : 5.17.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.0/user-manager-5.17.0.tar.xz : 659fab189915140e136c426d6a22852f9685ab85f1fec07a44faaa7a663c8d3d
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : A simple system settings module to manage the users of your system.
description: |
    A simple system settings module to manage the users of your system.
builddeps  :
    - pkgconfig(pwquality)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kauth-devel
    - kcmutils-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kiconthemes-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
rundeps    :
    - accountsservice
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
