name       : user-manager
version    : 5.11.4
release    : 8
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.4/user-manager-5.11.4.tar.xz : a5b031027edc248871a9e7fa6920167c605e4ffdf8d0272e5fa768cbb19ae657
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : A simple system settings module to manage the users of your system.
description: |
    A simple system settings module to manage the users of your system.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(pwquality)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kauth-devel
    - kcmutils-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kiconthemes-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
