name       : user-manager
version    : 5.11.2
release    : 6
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.2/user-manager-5.11.2.tar.xz : 99c4076a68b756db0841740b6afc5fac35c6712ec216830728489b232284dedf
license    : GPL-2.0
component  : desktop.kde.core
summary    : A simple system settings module to manage the users of your system.
description: |
    A simple system settings module to manage the users of your system.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(pwquality)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kauth-devel
    - kcmutils-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kiconthemes-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
