name       : user-manager
version    : 5.11.5
release    : 10
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.5/user-manager-5.11.5.tar.xz : 449f648eee7124687432ad71d510cd2eefe59ee7b2d4653ef9cc64f1422098e4
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : A simple system settings module to manage the users of your system.
description: |
    A simple system settings module to manage the users of your system.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(pwquality)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kauth-devel
    - kcmutils-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kiconthemes-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
rundeps    :
    - accountsservice
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
