name       : user-manager
version    : 5.16.5
release    : 39
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.5/user-manager-5.16.5.tar.xz : e9df3ec2718de68b0b46d0b86f993fe450b236e13dda6219f350121f08f4c468
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : A simple system settings module to manage the users of your system.
description: |
    A simple system settings module to manage the users of your system.
builddeps  :
    - pkgconfig(pwquality)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kauth-devel
    - kcmutils-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kiconthemes-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
rundeps    :
    - accountsservice
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
