name       : user-manager
version    : 5.17.5
release    : 44
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.5/user-manager-5.17.5.tar.xz : 10ed3196063c7dfed3b3f25dd199a48ca39fa86db5d0126ec84a543b1c212f0d
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : A simple system settings module to manage the users of your system.
description: |
    A simple system settings module to manage the users of your system.
builddeps  :
    - pkgconfig(pwquality)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kauth-devel
    - kcmutils-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kiconthemes-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
rundeps    :
    - accountsservice
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
