name       : user-manager
version    : 5.19.3
release    : 51
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.3/user-manager-5.19.3.tar.xz : 7e0ac9b696941ce394bc88e68c1fc09ce30e044940c2ff421cc95fa2592091ac
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : A simple system settings module to manage the users of your system.
description: |
    A simple system settings module to manage the users of your system.
builddeps  :
    - pkgconfig(pwquality)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kauth-devel
    - kcmutils-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
rundeps    :
    - accountsservice
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
