name       : user-manager
version    : 5.10.1
release    : 2
source     :
    - https://download.kde.org/stable/plasma/5.10.1/user-manager-5.10.1.tar.xz : 4abce606985d834bfa6163eab2fedee7a0f679369b78a39745d8c95cf598b100
license    : GPL-2.0
component  : desktop.kde.core
summary    : A simple system settings module to manage the users of your system.
description: |
    A simple system settings module to manage the users of your system.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(pwquality)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kauth-devel
    - kcmutils-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kiconthemes-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
