name       : user-manager
version    : 5.16.3
release    : 37
source     :
    - https://cdn.download.kde.org/stable/plasma/5.16.3/user-manager-5.16.3.tar.xz : 9d71980a976e5f37ac9e324d83e9c4de533cd4e77add66f9fdee7c5a0ec9ec0c
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : A simple system settings module to manage the users of your system.
description: |
    A simple system settings module to manage the users of your system.
builddeps  :
    - pkgconfig(pwquality)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kauth-devel
    - kcmutils-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kiconthemes-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
rundeps    :
    - accountsservice
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
