name       : user-manager
version    : 5.19.5
release    : 54
source     :
    - https://cdn.download.kde.org/stable/plasma/5.19.5/user-manager-5.19.5.tar.xz : 39260b2575f6287c8086984417bba18682ca2ba3840d93f95667d0d2faa461cc
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : A simple system settings module to manage the users of your system.
description: |
    A simple system settings module to manage the users of your system.
builddeps  :
    - pkgconfig(pwquality)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kauth-devel
    - kcmutils-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
rundeps    :
    - accountsservice
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
