name       : user-manager
version    : 5.18.5
release    : 49
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.5/user-manager-5.18.5.tar.xz : 741d293947fa3fb3966f047bab121597bf1071be010684daff4a91626cf54484
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    : GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : A simple system settings module to manage the users of your system.
description: |
    A simple system settings module to manage the users of your system.
builddeps  :
    - pkgconfig(pwquality)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kauth-devel
    - kcmutils-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
rundeps    :
    - accountsservice
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
